<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Perbandingan Smoothing, ARIMA, dan ARIMAX untuk prediksi harga minyak mentah</title>
  <meta name="description" content="Laporan tugas akhir MPDW Semester Genap 2021-2022" />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Perbandingan Smoothing, ARIMA, dan ARIMAX untuk prediksi harga minyak mentah" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Laporan tugas akhir MPDW Semester Genap 2021-2022" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Perbandingan Smoothing, ARIMA, dan ARIMAX untuk prediksi harga minyak mentah" />
  
  <meta name="twitter:description" content="Laporan tugas akhir MPDW Semester Genap 2021-2022" />
  

<meta name="author" content="Kelompok 10" />


<meta name="date" content="2022-04-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="pemulusan.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Laporan tugas akhir MPDW</a></li>

<li class="divider"></li>
<li><a href="pendahuluan.html#pendahuluan">Pendahuluan<span></span></a>
<ul>
<li><a href="pendahuluan.html#struktur-penelitian">Struktur penelitian<span></span></a></li>
<li><a href="pendahuluan.html#ekstraksi-data">Ekstraksi data<span></span></a></li>
<li class="chapter" data-level="0.1" data-path="pendahuluan.html"><a href="pendahuluan.html"><i class="fa fa-check"></i><b>0.1</b> Pola-pola data dan stasioneritas<span></span></a></li>
<li class="chapter" data-level="0.2" data-path="pendahuluan.html"><a href="pendahuluan.html#identifikasi-model"><i class="fa fa-check"></i><b>0.2</b> Identifikasi model<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="pemulusan.html"><a href="pemulusan.html"><i class="fa fa-check"></i><b>1</b> Pemulusan<span></span></a></li>
<li class="chapter" data-level="2" data-path="pemodelan.html"><a href="pemodelan.html"><i class="fa fa-check"></i><b>2</b> Pemodelan<span></span></a></li>
<li><a href="references.html#references">References<span></span></a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Perbandingan Smoothing, ARIMA, dan ARIMAX untuk prediksi harga minyak mentah</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Perbandingan Smoothing, ARIMA, dan ARIMAX untuk prediksi harga minyak mentah</h1>
<p class="author"><em>Kelompok 10</em></p>
<p class="date"><em>2022-04-06</em></p>
</div>
<div id="pendahuluan" class="section level1 unnumbered hasAnchor">
<h1>Pendahuluan<a href="pendahuluan.html#pendahuluan" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="struktur-penelitian" class="section level2 unnumbered hasAnchor">
<h2>Struktur penelitian<a href="pendahuluan.html#struktur-penelitian" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Laporan ini akan membandingkan beberapa metode peralaman deret waktu untuk data harga minyak mentah. Metode tersebut akan dilatih menggunakan harga minyak mentah dari tahun 2009 sampai 2016, lalu diuji dengan meramal harga minyak mentah tahun 2017. Pembagian tersebut juga dilakukan di <span class="citation">(<a href="#ref-He2018" role="doc-biblioref">He 2018</a>)</span>, yang membandingkan model deret waktu seperti pemulusan dan ARIMA dengan model pembelajaran mesin (SVM). Berbeda dengan penelitian tersebut, penelitian ini akan menambahkan jenis pemulusan yang dipakai, serta mencoba menambahkan pengaruh peubah bebas <em>dummy</em> yang memodelkan efek hari setelah libur, peubahan struktural pada rezim harga minyak, dan lain-lain. Sekarang, penulisan laporan masih dalam tahap praproses dan eksplorasi data.</p>
</div>
<div id="ekstraksi-data" class="section level2 unnumbered hasAnchor">
<h2>Ekstraksi data<a href="pendahuluan.html#ekstraksi-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Dataset yang digunakan sebagai berikut:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="pendahuluan.html#cb1-1" aria-hidden="true" tabindex="-1"></a>crude<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">&quot;crude.csv&quot;</span>,<span class="at">sep=</span><span class="st">&quot;;&quot;</span>)</span></code></pre></div>
<p>Beberapa observasi dari dataset tersebut dapat diperlihatkan untuk memberi gambaran mengenai data. Peubah yang akan dimodelkan adalah harga <em>close</em>, atau harga minyak saat pasar ditutup:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="pendahuluan.html#cb2-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(crude,<span class="at">n=</span><span class="dv">5</span>))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">X</th>
<th align="right">CL.F.Open</th>
<th align="right">CL.F.High</th>
<th align="right">CL.F.Low</th>
<th align="right">CL.F.Close</th>
<th align="right">CL.F.Volume</th>
<th align="right">CL.F.Adjusted</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">23/08/2000</td>
<td align="right">31.95</td>
<td align="right">32.80</td>
<td align="right">31.95</td>
<td align="right">32.05</td>
<td align="right">79385</td>
<td align="right">32.05</td>
</tr>
<tr class="even">
<td align="left">24/08/2000</td>
<td align="right">31.90</td>
<td align="right">32.24</td>
<td align="right">31.40</td>
<td align="right">31.63</td>
<td align="right">72978</td>
<td align="right">31.63</td>
</tr>
<tr class="odd">
<td align="left">25/08/2000</td>
<td align="right">31.70</td>
<td align="right">32.10</td>
<td align="right">31.32</td>
<td align="right">32.05</td>
<td align="right">44601</td>
<td align="right">32.05</td>
</tr>
<tr class="even">
<td align="left">28/08/2000</td>
<td align="right">32.04</td>
<td align="right">32.92</td>
<td align="right">31.86</td>
<td align="right">32.87</td>
<td align="right">46770</td>
<td align="right">32.87</td>
</tr>
<tr class="odd">
<td align="left">29/08/2000</td>
<td align="right">32.82</td>
<td align="right">33.03</td>
<td align="right">32.56</td>
<td align="right">32.72</td>
<td align="right">49131</td>
<td align="right">32.72</td>
</tr>
</tbody>
</table>
<p>Terlihat bahwa peubah yang menandakan tanggal memiliki format hari/bulan/tahun. Ubah peubah tersebut menjadi tipe data date dengan format yang tepat, lalu lakukan pembagian:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="pendahuluan.html#cb3-1" aria-hidden="true" tabindex="-1"></a>crude<span class="sc">$</span>X<span class="ot">&lt;-</span><span class="fu">as.Date</span>(crude<span class="sc">$</span>X, <span class="at">format=</span><span class="st">&quot;%d/%m/%Y&quot;</span>)</span>
<span id="cb3-2"><a href="pendahuluan.html#cb3-2" aria-hidden="true" tabindex="-1"></a>crudetrain<span class="ot">&lt;-</span><span class="fu">subset</span>(crude,</span>
<span id="cb3-3"><a href="pendahuluan.html#cb3-3" aria-hidden="true" tabindex="-1"></a>                         X <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&#39;2009-01-01&#39;</span>) <span class="sc">&amp;</span></span>
<span id="cb3-4"><a href="pendahuluan.html#cb3-4" aria-hidden="true" tabindex="-1"></a>                         X <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">&#39;2016-12-31&#39;</span>))</span>
<span id="cb3-5"><a href="pendahuluan.html#cb3-5" aria-hidden="true" tabindex="-1"></a>crudetest<span class="ot">&lt;-</span><span class="fu">subset</span>(crude,</span>
<span id="cb3-6"><a href="pendahuluan.html#cb3-6" aria-hidden="true" tabindex="-1"></a>                         X <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">&#39;2017-01-01&#39;</span>) <span class="sc">&amp;</span></span>
<span id="cb3-7"><a href="pendahuluan.html#cb3-7" aria-hidden="true" tabindex="-1"></a>                         X <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">&#39;2017-12-31&#39;</span>))</span></code></pre></div>
<p>Sudah diambil data yang relevan untuk diteliti.</p>
<pre><code>
&lt;!--chapter:end:index.Rmd--&gt;

# Praproses dan Eksplorasi Data

Bagian ini akan membahas beberapa hal:

1. Permasalahan interval waktu data
2. Latar belakang fluktuasi harga minyak
3. Ekstraksi peubah *dummy* untuk memodelkan efek hari libur dan perubahan struktural
4. Pola data time series dan kestasioneran
5. Identifikasi model.

## Interval waktu data

Dari melihat 10 tanggal pertama yang dicatat di dataset harga minyak:

```r
knitr::kable(head(crudetrain[,c(1,5)],n=10),
             col.names = c(&quot;Tanggal Pengamatan&quot;,&quot;Harga Close&quot;))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Tanggal Pengamatan</th>
<th align="right">Harga Close</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2166</td>
<td align="left">2009-01-02</td>
<td align="right">46.34</td>
</tr>
<tr class="even">
<td align="left">2167</td>
<td align="left">2009-01-05</td>
<td align="right">48.81</td>
</tr>
<tr class="odd">
<td align="left">2168</td>
<td align="left">2009-01-06</td>
<td align="right">48.58</td>
</tr>
<tr class="even">
<td align="left">2169</td>
<td align="left">2009-01-07</td>
<td align="right">42.63</td>
</tr>
<tr class="odd">
<td align="left">2170</td>
<td align="left">2009-01-08</td>
<td align="right">41.70</td>
</tr>
<tr class="even">
<td align="left">2171</td>
<td align="left">2009-01-09</td>
<td align="right">40.83</td>
</tr>
<tr class="odd">
<td align="left">2172</td>
<td align="left">2009-01-12</td>
<td align="right">37.59</td>
</tr>
<tr class="even">
<td align="left">2173</td>
<td align="left">2009-01-13</td>
<td align="right">37.78</td>
</tr>
<tr class="odd">
<td align="left">2174</td>
<td align="left">2009-01-14</td>
<td align="right">37.28</td>
</tr>
<tr class="even">
<td align="left">2175</td>
<td align="left">2009-01-15</td>
<td align="right">35.40</td>
</tr>
</tbody>
</table>
<p>Terlihat bahwa rentang waktu pengamatan data tidak sama. Misal, tidak ada pengamatan saat 1 Januari 2009 karena ada libur tahun baru. Selain itu, ada lompatan dari 2 Januari 2009 ke 5 Januari 2009. Dalam kata lain, harga minyak tidak diamati pada tanggal 3 dan 4 Januari 2009, yang merupakan akhir minggu (hari Sabtu dan Minggu). Pola yang sama terulang di data deret waktu tersebut bagi akhir minggu dan hari libur lainnya - pasar ditutup sehingga harga minyak tidak ada.</p>
<p>Situasi ini dapat ditangani dengan tiga cara umum:</p>
<ol style="list-style-type: decimal">
<li>Abaikan rentang waktu harian yang tidak sama. Gunakan <em>trading days</em> atau hari kerja sebagai rentang waktu.</li>
<li>Isi data akhir minggu dan hari libur menggunakan suatu bentuk interpolasi.</li>
<li>Agregasikan data menjadi data mingguan, bulanan, atau tahunan.</li>
</ol>
<p>Cara pertama sering dipakai dalam peramalan deret waktu. Walaupun tidak ada data hari libur dan akhir minggu, nilai harian reksadana saham CREF dari tahun 2004 sampai 2006 dimodelkan dengan menggangap data tersebut memiliki rentang waktu yang sama <span class="citation">(<a href="#ref-cryer_time_2008" role="doc-biblioref">Cryer dan Chan 2008</a>)</span>. Pemodelan harga emas harian dari tahun 1985 sampai 1989 juga hanya menggunakan <em>trading days</em>. Dilakukan interpolasi, tetapi hanya untuk data hilang di <em>trading days</em> <span class="citation">(<a href="#ref-fpp2" role="doc-biblioref">Hyndman dan Athanasopoulos 2018</a>)</span>. Peramalan harga minyak <span class="citation">(<a href="#ref-fouroil" role="doc-biblioref">Elshendy <em>et al.</em> 2018</a>)</span> juga menggunakan data selama 84 hari kerja saja.</p>
<p>Namun, juga ada justifikasi untuk interpolasi data. Interpolasi data dilakukan saat observasi tersebut dianggap memiliki nilai suatu peubah, tetapi tidak dapat diobservasi. Misal, tidak perlu melakukan interpolasi peubah gaji untuk seorang anak karena dia tidak mungkin bekerja. Dalam kasus ini, harga minyak di hari libur mungkin saja memiliki nilai. Pasar saham dan sekuritas sering mengalami <em>after-hours trading</em>; saat hal tersebut terjadi, harga berubah <span class="citation">(<a href="#ref-barclay_price_2015" role="doc-biblioref">Barclay dan Hendershott 2015</a>)</span>. Walaupun begitu, bentuk proses tersebut harus diasumsikan untuk diinterpolasi. Misal, jika menggunakan interpolasi linear, diasumsikan bahwa pergerakan harga dari hari kerja ke hari kerja lainnya di hari libur konstan. Ini belum tentu benar - mungkin saja di hari Sabtu, harga masih naik dari hari Jumat, tetapi harga turun di hari Minggu. Interpolasi linear akan mengasumsikan harga turun di Sabtu dan Minggu. Oleh karena itu, interpolasi akan menghasilkan aproksimasi kasar dari proses <em>after-hours trading</em>.</p>
<p>Agregasi data dapat menyelesaikan masalah tersebut karena hasil agregasi dianggap memiliki rentang waktu sama. Misal, mingguan atau bulanan. Agregasi ini harus mengikuti beberapa aturan <span class="citation">(<a href="#ref-soverflow" role="doc-biblioref">(https://stackoverflow.com/users/1494637/stefan) 2019</a>)</span>. Untuk harga <em>opening</em>, akan diambil data harga open dari hari pertama di minggu/bulan tersebut - harga tersebut merupakan harga minyak saat pasar dibuka. Harga <em>close</em> diambil dari harga close hari terakhir di minggu/bulan tersebut - harga tersebut merupakan harga minyak saat pasar ditutup. Harga maksimum dan minimum memiliki logika yang mirip.</p>
<p>Namun, agregasi data belum tentu menyelesaikan masalah rentang waktu tak sama. Ada beberapa bulan yang memiliki 28, 30, dan 31 hari. Ini berarti rentang pengamatan satu bulan dapat berarti beberapa jarak waktu yang berbeda. Data mingguan selalu memiliki rentang 7 hari jika data diambil dari hari yang sama di setiap minggu. Dalam kasus ini, ini berarti mengasumsikan data di hari Jumat selalu ada untuk <em>closing</em>, atau data hari Senin selalu ada. Mengingat rentang waktu yang cukup lama (8 tahun), kemungkinan besar ada data di hari-hari tersebut yang tidak ada.</p>
<p>Dari beberapa pertimbangan tersebut, data akan dibiarkan dalam rentang waktu hari kerja. Metode ini sering dilakukan dalam penelitian dan relatif sederhana - tidak perlu dilakukan pemrosesan tambahan. Tidak perlu juga mengasumsikan struktur tertentu pada data hari libur.</p>
<p>Namun, bisa jadi tidak adanya data hari libur tersebut membuat bias dalam model - misal, setelah hari libur biasanya ada lebih banyak pengunjung di toko-toko yang baru buka <span class="citation">(<a href="#ref-fpp2" role="doc-biblioref">Hyndman dan Athanasopoulos 2018</a>)</span>. Untuk memodelkan efek hari libur tersebut, akan dibuat variabel <em>dummy</em> di hari-hari setelah libur dan akhir minggu. Variabel ini memodelkan fakta bahwa harga di hari Senin, misal, merespon informasi dari hari Sabtu, Minggu, dan Senin, tidak Senin saja.</p>
<p>Sebelum itu, masih ada data hilang di hari kerja yang diimputasi:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="pendahuluan.html#cb5-1" aria-hidden="true" tabindex="-1"></a>name<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">&quot;Latih&quot;</span>,<span class="st">&quot;Uji&quot;</span>)</span>
<span id="cb5-2"><a href="pendahuluan.html#cb5-2" aria-hidden="true" tabindex="-1"></a>NAs<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fu">sum</span>(<span class="fu">is.na</span>(crudetrain<span class="sc">$</span>CL.F.Close)),<span class="fu">sum</span>(<span class="fu">is.na</span>(crudetest<span class="sc">$</span>CL.F.Close)))</span>
<span id="cb5-3"><a href="pendahuluan.html#cb5-3" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">cbind</span>(name,NAs),</span>
<span id="cb5-4"><a href="pendahuluan.html#cb5-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;Data&quot;</span>,<span class="st">&quot;Jumlah NA&quot;</span>))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">Data</th>
<th align="left">Jumlah NA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Latih</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">Uji</td>
<td align="left">0</td>
</tr>
</tbody>
</table>
<p>Data hilang di data latih akan tetap di-interpolasi dengan fungsi <code>na_interpolation</code> dari package <code>imputeTS</code> <span class="citation">(<a href="#ref-R-imputeTS" role="doc-biblioref">Moritz dan Gatscha 2021</a>)</span>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="pendahuluan.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(imputeTS)</span>
<span id="cb6-2"><a href="pendahuluan.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#interpolasi</span></span>
<span id="cb6-3"><a href="pendahuluan.html#cb6-3" aria-hidden="true" tabindex="-1"></a>crudetrain<span class="sc">$</span>fixed  <span class="ot">&lt;-</span>  <span class="fu">na_interpolation</span>(crudetrain<span class="sc">$</span><span class="st">`</span><span class="at">CL.F.Close</span><span class="st">`</span>)</span>
<span id="cb6-4"><a href="pendahuluan.html#cb6-4" aria-hidden="true" tabindex="-1"></a>crudetest<span class="sc">$</span>fixed   <span class="ot">&lt;-</span>  <span class="fu">na_interpolation</span>(crudetest<span class="sc">$</span><span class="st">`</span><span class="at">CL.F.Close</span><span class="st">`</span>)</span>
<span id="cb6-5"><a href="pendahuluan.html#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="pendahuluan.html#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#plot</span></span>
<span id="cb6-7"><a href="pendahuluan.html#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot_na_imputations</span>(crudetrain<span class="sc">$</span><span class="st">`</span><span class="at">CL.F.Close</span><span class="st">`</span>, crudetrain<span class="sc">$</span>fixed)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Untuk mengekstraksi peubah <em>dummy</em> yang memodelkan efek hari setelah libur, buat sederet data yang berisi semua hari dari tahun 2009 sampai 2017, lalu merge:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="pendahuluan.html#cb7-1" aria-hidden="true" tabindex="-1"></a>crudeDates<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">X=</span><span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2009-01-01&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2017-12-31&quot;</span>), <span class="at">by=</span><span class="st">&quot;days&quot;</span>))</span>
<span id="cb7-2"><a href="pendahuluan.html#cb7-2" aria-hidden="true" tabindex="-1"></a>crude0917<span class="ot">&lt;-</span><span class="fu">rbind</span>(crudetrain,crudetest)</span>
<span id="cb7-3"><a href="pendahuluan.html#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="pendahuluan.html#cb7-4" aria-hidden="true" tabindex="-1"></a>crudeall<span class="ot">&lt;-</span><span class="fu">merge</span>(crudeDates,crude0917,<span class="at">by=</span><span class="st">&quot;X&quot;</span>,<span class="at">all.x=</span>T)</span>
<span id="cb7-5"><a href="pendahuluan.html#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="pendahuluan.html#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(crudeall<span class="sc">$</span>fixed))</span></code></pre></div>
<pre><code>## [1] 1021</code></pre>
<p>Terdapat 1021 data hilang. Buat deret hari akhir minggu dari tahun 2009 sampai 2017. Hari Sabtu pertama di dataset ini adalah Januari 3, 2009:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="pendahuluan.html#cb9-1" aria-hidden="true" tabindex="-1"></a>sats<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2009-01-03&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2017-12-31&quot;</span>), <span class="at">by=</span><span class="st">&quot;weeks&quot;</span>)</span>
<span id="cb9-2"><a href="pendahuluan.html#cb9-2" aria-hidden="true" tabindex="-1"></a>suns<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">&quot;2009-01-04&quot;</span>), <span class="fu">as.Date</span>(<span class="st">&quot;2017-12-31&quot;</span>), <span class="at">by=</span><span class="st">&quot;weeks&quot;</span>)</span>
<span id="cb9-3"><a href="pendahuluan.html#cb9-3" aria-hidden="true" tabindex="-1"></a>weekends<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">X=</span><span class="fu">c</span>(sats,suns))</span>
<span id="cb9-4"><a href="pendahuluan.html#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="pendahuluan.html#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(weekends)</span></code></pre></div>
<pre><code>## [1] 940</code></pre>
<p>Ada 940 hari yang merupakan akhir minggu dari 1024 hari libur. Untuk mendapat data hari libur nasional di bursa saham New York, gunakan fungsi <code>holidayNYSE</code> dari package <code>timeDate</code> <span class="citation">(<a href="#ref-R-timeDate" role="doc-biblioref">Wuertz <em>et al.</em> 2018</a>)</span>. Dengan menggunakan <code>anti_join</code> dari <code>dplyr</code> <span class="citation">(<a href="#ref-R-dplyr" role="doc-biblioref">Wickham <em>et al.</em> 2022</a>)</span> yang menghasilkan:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="pendahuluan.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(timeDate)</span>
<span id="cb11-2"><a href="pendahuluan.html#cb11-2" aria-hidden="true" tabindex="-1"></a>hols<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">X=</span><span class="fu">as.Date</span>(<span class="fu">holidayNYSE</span>(<span class="at">year=</span><span class="fu">seq</span>(<span class="dv">2009</span>,<span class="dv">2017</span>,<span class="dv">1</span>))))</span>
<span id="cb11-3"><a href="pendahuluan.html#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="pendahuluan.html#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dplyr<span class="sc">::</span><span class="fu">anti_join</span>(weekends,hols,<span class="at">by=</span><span class="st">&quot;X&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 940</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="pendahuluan.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dplyr<span class="sc">::</span><span class="fu">anti_join</span>(hols,weekends,<span class="at">by=</span><span class="st">&quot;X&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 80</code></pre>
<p>Terlihat bahwa 1020 dari data hilang dapat dijelaskan oleh libur nasional dan akhir minggu. Hanya 1 dari data hilang yang tidak dapat dijelaskan. Buat deret hari Senin dari tahun 2009 sampai 2017, dan hari setelah hari libur nasional.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="pendahuluan.html#cb15-1" aria-hidden="true" tabindex="-1"></a>mons<span class="ot">&lt;-</span><span class="fu">data.frame</span>(<span class="at">X=</span>suns<span class="sc">+</span><span class="dv">1</span>)<span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="pendahuluan.html#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dumMon=</span><span class="dv">1</span>)</span>
<span id="cb15-3"><a href="pendahuluan.html#cb15-3" aria-hidden="true" tabindex="-1"></a>posthol<span class="ot">&lt;-</span>hols<span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="pendahuluan.html#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">X=</span>X<span class="sc">+</span><span class="dv">1</span>,</span>
<span id="cb15-5"><a href="pendahuluan.html#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">dumHol=</span><span class="dv">1</span>)</span></code></pre></div>
<p>Lalu, merge data crude dengan data hari Senin dan hari setelah libur nasional.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="pendahuluan.html#cb16-1" aria-hidden="true" tabindex="-1"></a>crudeDummies<span class="ot">&lt;-</span> crude0917<span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="pendahuluan.html#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">merge</span>(mons,<span class="at">by=</span><span class="st">&quot;X&quot;</span>,<span class="at">all.x=</span>T) <span class="sc">%&gt;%</span> <span class="fu">merge</span>(posthol, <span class="at">by=</span><span class="st">&quot;X&quot;</span>,<span class="at">all.x=</span>T) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="pendahuluan.html#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dumMon=</span><span class="fu">ifelse</span>(<span class="fu">is.na</span>(dumMon),<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb16-4"><a href="pendahuluan.html#cb16-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">dumHol=</span><span class="fu">ifelse</span>(<span class="fu">is.na</span>(dumHol),<span class="dv">0</span>,<span class="dv">1</span>))</span></code></pre></div>
<p>Peubah <em>dummy</em> untuk memodelkan efek pasar dibuka saat hari senin dan setelah libur telah dibuat. Peubah tersebut sebenarnya tidak terlalu berkorelasi dengan harga minyak, jadi mungkin saja efek-efek tersebut tidak ada:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="pendahuluan.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(crudeDummies<span class="sc">$</span>fixed,crudeDummies<span class="sc">$</span>dumHol,<span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## [1] -0.002640834</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="pendahuluan.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(crudeDummies<span class="sc">$</span>fixed,crudeDummies<span class="sc">$</span>dumMon,<span class="at">method=</span><span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## [1] -0.002223559</code></pre>
</div>
<div id="pola-pola-data-dan-stasioneritas" class="section level2 hasAnchor" number="0.1">
<h2><span class="header-section-number">0.1</span> Pola-pola data dan stasioneritas<a href="pendahuluan.html#pola-pola-data-dan-stasioneritas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Plot dari data tersebut dibuat menggunakan <code>ggplot2</code> <span class="citation">(<a href="#ref-R-ggplot2" role="doc-biblioref">Wickham <em>et al.</em> 2021</a>)</span>:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="pendahuluan.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb21-2"><a href="pendahuluan.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crude0917, <span class="fu">aes</span>(<span class="at">x=</span>X, <span class="at">y=</span>fixed)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="pendahuluan.html#cb21-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb21-4"><a href="pendahuluan.html#cb21-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggtitle</span>(<span class="st">&quot;Harga Minyak (CL.F. Close)&quot;</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">&quot;Waktu&quot;</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Harga&quot;</span>)<span class="sc">+</span></span>
<span id="cb21-5"><a href="pendahuluan.html#cb21-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Terlihat bahwa data memiliki pola campuran. Secara kasar, terlihat tren naik pada tahun 2009-2011. Lalu, dari tahun 2011-2014 harga minyak siklik, tetapi rataannya stasioner, kira-kira di atas 75 dolar. Harga minyak turun drastis dari tahun 2014-2016. Terakhir, harga minyak naik sedikit lalu stasioner lalu naik sedikit lagi di tahun 2016-2018. Pola-pola tersebut dapat dilihat setelah dilakukan dekomposisi melalui <code>dplyr</code> <span class="citation">(<a href="#ref-R-dplyr" role="doc-biblioref">Wickham <em>et al.</em> 2022</a>)</span>:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="pendahuluan.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-2"><a href="pendahuluan.html#cb22-2" aria-hidden="true" tabindex="-1"></a>cbbPalette <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;#000000&quot;</span>, <span class="st">&quot;#E69F00&quot;</span>, <span class="st">&quot;#56B4E9&quot;</span>, <span class="st">&quot;#009E73&quot;</span>, </span>
<span id="cb22-3"><a href="pendahuluan.html#cb22-3" aria-hidden="true" tabindex="-1"></a>                <span class="st">&quot;#F0E442&quot;</span>, <span class="st">&quot;#0072B2&quot;</span>, <span class="st">&quot;#D55E00&quot;</span>, <span class="st">&quot;#CC79A7&quot;</span>)</span>
<span id="cb22-4"><a href="pendahuluan.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co">#palet yang inklusif pada buta warna</span></span>
<span id="cb22-5"><a href="pendahuluan.html#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="pendahuluan.html#cb22-6" aria-hidden="true" tabindex="-1"></a>crude0917 <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="pendahuluan.html#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Segmen=</span></span>
<span id="cb22-8"><a href="pendahuluan.html#cb22-8" aria-hidden="true" tabindex="-1"></a>           <span class="fu">ifelse</span>(X<span class="sc">&lt;=</span><span class="fu">as.Date</span>(<span class="st">&#39;2010-12-31&#39;</span>),<span class="st">&quot;1&quot;</span>,</span>
<span id="cb22-9"><a href="pendahuluan.html#cb22-9" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">ifelse</span>(X<span class="sc">&lt;=</span><span class="fu">as.Date</span>(<span class="st">&#39;2014-06-01&#39;</span>),<span class="st">&quot;2&quot;</span>,</span>
<span id="cb22-10"><a href="pendahuluan.html#cb22-10" aria-hidden="true" tabindex="-1"></a>                                      <span class="fu">ifelse</span>(X<span class="sc">&lt;=</span><span class="fu">as.Date</span>(<span class="st">&#39;2016-01-01&#39;</span>),<span class="st">&quot;3&quot;</span>,<span class="st">&quot;4&quot;</span>)</span>
<span id="cb22-11"><a href="pendahuluan.html#cb22-11" aria-hidden="true" tabindex="-1"></a>                                 ))<span class="co">#buat segmentasi </span></span>
<span id="cb22-12"><a href="pendahuluan.html#cb22-12" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb22-13"><a href="pendahuluan.html#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>fixed))<span class="sc">+</span></span>
<span id="cb22-14"><a href="pendahuluan.html#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">color=</span>Segmen))<span class="sc">+</span><span class="fu">scale_color_manual</span>(<span class="at">values=</span>cbbPalette)<span class="sc">+</span></span>
<span id="cb22-15"><a href="pendahuluan.html#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;Segmentasi Harga Minyak (CL.F Close)&quot;</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">&quot;Waktu&quot;</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Harga&quot;</span>)<span class="sc">+</span></span>
<span id="cb22-16"><a href="pendahuluan.html#cb22-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Secara lebih formal, dapat dicari titik-titik perubahan struktural di deret waktu tersebut menggunakan fungsi <code>breakpoints</code> dari package <code>strucchange</code> <span class="citation">(<a href="#ref-R-strucchange" role="doc-biblioref">Zeileis <em>et al.</em> 2019</a>)</span>. Jika kita menggunakan model rata-rata yang sederhana seperti <code>lm(y~1)</code>, terlihat bahwa dibutuhkan dua break point untuk data tersebut:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="pendahuluan.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(strucchange)</span>
<span id="cb23-2"><a href="pendahuluan.html#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="pendahuluan.html#cb23-3" aria-hidden="true" tabindex="-1"></a>breakOil<span class="ot">&lt;-</span><span class="fu">breakpoints</span>(crude0917<span class="sc">$</span>fixed<span class="sc">~</span><span class="dv">1</span>)</span>
<span id="cb23-4"><a href="pendahuluan.html#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(breakOil)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>RSS dan BIC turun drastis setelah menambah dua break point. Break point tersebut dapat diperlihatkan sebagai berikut:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="pendahuluan.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(breakOil)</span></code></pre></div>
<pre><code>## 
##   Optimal (m+1)-segment partition: 
## 
## Call:
## breakpoints.formula(formula = crude0917$fixed ~ 1)
## 
## Breakpoints at observation number:
##                               
## m = 1                1488     
## m = 2   461          1488     
## m = 3   440     1119 1488     
## m = 4   440     1119 1488 1927
## m = 5   440 779 1119 1488 1927
## 
## Corresponding to breakdates:
##                                                                               
## m = 1                                                         0.65666372462489
## m = 2   0.203442188879082                                     0.65666372462489
## m = 3   0.194174757281553                   0.493821712268314 0.65666372462489
## m = 4   0.194174757281553                   0.493821712268314 0.65666372462489
## m = 5   0.194174757281553 0.343777581641659 0.493821712268314 0.65666372462489
##                          
## m = 1                    
## m = 2                    
## m = 3                    
## m = 4   0.850397175639894
## m = 5   0.850397175639894
## 
## Fit:
##                                                    
## m   0       1       2       3       4       5      
## RSS 1188455  394415  176635  172118  169301  169294
## BIC   20637   18153   16348   16305   16283   16298</code></pre>
<p>Breakpoint berada di observasi ke-461 dan 1488 jika menggunakan dua breakpoint. Peubah yang menandakan segmen-segmen yang berbeda dapat dibuat (segmen pertama adalah observasi sebelum observasi ke-461, segmen kedua berada di antara observasi ke-461 dan 1488, dan segmen terakhir adalah observasi setelah observasi 1488).</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="pendahuluan.html#cb26-1" aria-hidden="true" tabindex="-1"></a>crudesegmented<span class="ot">&lt;-</span> crudeDummies <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">B1=</span><span class="fu">ifelse</span>(X <span class="sc">&gt;=</span> <span class="fu">nth</span>(X,<span class="dv">461</span>) <span class="sc">&amp;</span> X <span class="sc">&lt;=</span> <span class="fu">nth</span>(X,<span class="dv">1488</span>),<span class="dv">1</span>,<span class="dv">0</span>),</span>
<span id="cb26-2"><a href="pendahuluan.html#cb26-2" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">B2=</span><span class="fu">ifelse</span>(X <span class="sc">&gt;</span> <span class="fu">nth</span>(X,<span class="dv">1488</span>),<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb26-3"><a href="pendahuluan.html#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(crude0917, <span class="fu">aes</span>(<span class="at">x=</span>X, <span class="at">y=</span>fixed)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="pendahuluan.html#cb26-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb26-5"><a href="pendahuluan.html#cb26-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">nth</span>(crude0917<span class="sc">$</span>X,<span class="dv">461</span>), <span class="at">col=</span><span class="st">&quot;darkred&quot;</span>)<span class="sc">+</span></span>
<span id="cb26-6"><a href="pendahuluan.html#cb26-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">nth</span>(crude0917<span class="sc">$</span>X,<span class="dv">1488</span>), <span class="at">col=</span><span class="st">&quot;darkred&quot;</span>)<span class="sc">+</span></span>
<span id="cb26-7"><a href="pendahuluan.html#cb26-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ggtitle</span>(<span class="st">&quot;Harga Minyak (CL.F. Close)&quot;</span>)<span class="sc">+</span><span class="fu">xlab</span>(<span class="st">&quot;Waktu&quot;</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;Harga&quot;</span>)<span class="sc">+</span></span>
<span id="cb26-8"><a href="pendahuluan.html#cb26-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Segmentasi ini akan digunakan sebagai peubah <em>dummy</em> yang menjadi input model ARIMAX. Dapat dilihat matriks peubah <em>dummy</em> yang akan dipakai, termasuk segmentasi dan efek hari setelah libur:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="pendahuluan.html#cb27-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(crudesegmented[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">9</span><span class="sc">:</span><span class="dv">12</span>])</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">dumMon</th>
<th align="right">dumHol</th>
<th align="right">B1</th>
<th align="right">B2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>Dapat dilihat bahwa peubah tersebut berkorelasi cukup tinggi dengan harga minyak:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="pendahuluan.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(crudesegmented<span class="sc">$</span>fixed,crudesegmented<span class="sc">$</span>B1)</span></code></pre></div>
<pre><code>## [1] 0.8605528</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="pendahuluan.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(crudesegmented<span class="sc">$</span>fixed,crudesegmented<span class="sc">$</span>B2)</span></code></pre></div>
<pre><code>## [1] -0.8173909</code></pre>
<p>Selain segmentasi, plot menunjukkan bahwa data tersebut tidak stasioner. ACF juga memberikan kesimpulan yang sama, baik untuk data latih:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="pendahuluan.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(crudetrain<span class="sc">$</span>fixed)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>Dan data keseluruhan:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="pendahuluan.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(crude0917<span class="sc">$</span>fixed)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Kedua ACF menurun secara lambat.Untuk mengatasi hal tersebut, dapat dilakukan differencing:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="pendahuluan.html#cb34-1" aria-hidden="true" tabindex="-1"></a>crudetrain <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="pendahuluan.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">differenced=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(fixed,<span class="dv">1</span>)))<span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="pendahuluan.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>X,<span class="at">y=</span>differenced))<span class="sc">+</span></span>
<span id="cb34-4"><a href="pendahuluan.html#cb34-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb34-5"><a href="pendahuluan.html#cb34-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">2.5</span>,<span class="at">color=</span><span class="st">&quot;darkred&quot;</span>)<span class="sc">+</span></span>
<span id="cb34-6"><a href="pendahuluan.html#cb34-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="sc">-</span><span class="fl">2.5</span>,<span class="at">color=</span><span class="st">&quot;darkred&quot;</span>)<span class="sc">+</span></span>
<span id="cb34-7"><a href="pendahuluan.html#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values=</span>cbbPalette)<span class="sc">+</span></span>
<span id="cb34-8"><a href="pendahuluan.html#cb34-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">&quot;First Difference Harga Minyak (CL.F Close)&quot;</span>)<span class="sc">+</span></span>
<span id="cb34-9"><a href="pendahuluan.html#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">&quot;Waktu&quot;</span>)<span class="sc">+</span><span class="fu">ylab</span>(<span class="st">&quot;&quot;</span>)<span class="sc">+</span></span>
<span id="cb34-10"><a href="pendahuluan.html#cb34-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>Walaupun sudah tampak tidak ada tren, terlihat bahwa ada beberapa titik yang memiliki amplitudo lebih besar dari biasanya. Ini berarti data belum tentu stasioner dalam ragam, tetapi sudah stasioner dalam tren. Dapat dilihat ACF untuk memperkuat anggapan tersebut:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="pendahuluan.html#cb35-1" aria-hidden="true" tabindex="-1"></a>differenced<span class="ot">&lt;-</span><span class="fu">diff</span>(crudetrain<span class="sc">$</span>fixed,<span class="dv">1</span>)</span>
<span id="cb35-2"><a href="pendahuluan.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(differenced)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>Terlihat bahwa ACF cepat <em>cut off</em> sehingga data tampak stasioner. Dapat dilakukan uji Dickey-Fuller teraugmentasi untuk menguji kestasioneran secara formal. Uji ini diimplementasikan menggunakan fungsi <code>adf.test</code> library <code>aTSA</code> <span class="citation">(<a href="#ref-R-aTSA" role="doc-biblioref">Qiu 2015</a>)</span>:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="pendahuluan.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aTSA)</span>
<span id="cb36-2"><a href="pendahuluan.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">adf.test</span>(differenced)</span></code></pre></div>
<pre><code>## Augmented Dickey-Fuller Test 
## alternative: stationary 
##  
## Type 1: no drift no trend 
##      lag   ADF p.value
## [1,]   0 -46.5    0.01
## [2,]   1 -32.1    0.01
## [3,]   2 -26.3    0.01
## [4,]   3 -22.6    0.01
## [5,]   4 -20.3    0.01
## [6,]   5 -18.3    0.01
## [7,]   6 -17.0    0.01
## [8,]   7 -15.7    0.01
## Type 2: with drift no trend 
##      lag   ADF p.value
## [1,]   0 -46.5    0.01
## [2,]   1 -32.1    0.01
## [3,]   2 -26.3    0.01
## [4,]   3 -22.5    0.01
## [5,]   4 -20.3    0.01
## [6,]   5 -18.3    0.01
## [7,]   6 -17.0    0.01
## [8,]   7 -15.7    0.01
## Type 3: with drift and trend 
##      lag   ADF p.value
## [1,]   0 -46.5    0.01
## [2,]   1 -32.2    0.01
## [3,]   2 -26.3    0.01
## [4,]   3 -22.6    0.01
## [5,]   4 -20.4    0.01
## [6,]   5 -18.4    0.01
## [7,]   6 -17.1    0.01
## [8,]   7 -15.8    0.01
## ---- 
## Note: in fact, p.value = 0.01 means p.value &lt;= 0.01</code></pre>
<p>Di berbagai lag, terlihat bahwa data <em>first difference</em> sudah stasioner. Untuk mengatasi ragam yang tidak stasioner, mungkin saja digunakan model GARCH untuk sebagai alternatif dalam pemodelan.</p>
</div>
<div id="identifikasi-model" class="section level2 hasAnchor" number="0.2">
<h2><span class="header-section-number">0.2</span> Identifikasi model<a href="pendahuluan.html#identifikasi-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Sebagai langkah terakhir eksplorasi, dapat diidentifikasi beberapa model tentatif yang akan digunakan saat tahap pemodelan:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="pendahuluan.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">acf</span>(differenced)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<p>Walaupun tidak menyentuh garis signifikasi, autokorelasi di lag 1 relatif lebih tinggi dari autokorelasi di lag lainnya. Oleh karena itu, <span class="math inline">\(ARIMA(0,1,1)\)</span> dapat menjadi salah satu calon model.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="pendahuluan.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pacf</span>(differenced)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>Begitu juga untuk PACF, lag pertama tampak lebih tinggi dari lag setelahnya walaupun tidak melewati garis. <span class="math inline">\(ARIMA(1,1,0)\)</span> menjadi salah satu model tentatif. Lanjutkan dengan EACF:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="pendahuluan.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eacf</span>(differenced)</span></code></pre></div>
<pre><code>## AR/MA
##   0 1 2 3 4 5 6 7 8 9 10 11 12 13
## 0 o o o o o o o o o o o  o  o  o 
## 1 x o o o o o o o o o o  o  o  o 
## 2 x o o o o o o o o o o  o  o  o 
## 3 x x o o o o o o o o o  o  o  o 
## 4 x x o o o o o o o o o  o  o  o 
## 5 x x x x o o o o o o o  o  o  o 
## 6 x x x x x o o o o o o  o  o  o 
## 7 x x x x o o x o o o o  o  o  o</code></pre>
<p>Beberapa calon model yang muncul di EACF adalah <span class="math inline">\(ARIMA(0,1,0)\)</span>, <span class="math inline">\(ARIMA(0,1,1)\)</span>, <span class="math inline">\(ARIMA(1,1,1)\)</span>, dan <span class="math inline">\(ARIMA(2,1,1)\)</span>.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body">
<div id="ref-barclay_price_2015" class="csl-entry">
Barclay MJ, Hendershott T. 2015. Price <span>Discovery</span> and <span>Trading</span> <span>After</span> <span>Hours</span>. <em>The Review of Financial Studies</em>. 16(4):1041–1073.doi:<a href="https://doi.org/10.1093/rfs/hhg030">10.1093/rfs/hhg030</a>.
</div>
<div id="ref-cryer_time_2008" class="csl-entry">
Cryer JD, Chan KS. 2008. <em>Time <span>Series</span> <span>Analysis</span>: <span>With</span> <span>Applications</span> in <span>R</span></em>. Springer New York. (Springer <span>Texts</span> in <span>Statistics</span>).
</div>
<div id="ref-fouroil" class="csl-entry">
Elshendy M, Colladon AF, Battistoni E, Gloor PA. 2018. Using four different online media sources to forecast the crude oil price. <em>Journal of Information Science</em>. 44(3):408–421.doi:<a href="https://doi.org/10.1177/0165551517698298">10.1177/0165551517698298</a>.
</div>
<div id="ref-He2018" class="csl-entry">
He XJ. 2018. Crude Oil Prices Forecasting: Time Series vs. SVR Models. <em>Journal of International Technology and Information Management</em>. 27(2):25–42.
</div>
<div id="ref-soverflow" class="csl-entry">
(https://stackoverflow.com/users/1494637/stefan) S. 2019. converting daily stock data to weekly-based via pandas in Python. <em>Stack Overflow</em>. [diunduh 2019 Jan 28]. Tersedia pada: <a href="https://stackoverflow.com/questions/34597926/converting-daily-stock-data-to-weekly-based-via-pandas-in-python">https://stackoverflow.com/questions/34597926/converting-daily-stock-data-to-weekly-based-via-pandas-in-python</a>
</div>
<div id="ref-fpp2" class="csl-entry">
Hyndman RJ, Athanasopoulos G. 2018. <em>Forecasting: Principles and Practice</em>. ed ke-2. Australia: OTexts.
</div>
<div id="ref-R-imputeTS" class="csl-entry">
Moritz S, Gatscha S. 2021. <em>imputeTS: Time Series Missing Value Imputation</em>. Ed ke-R package version 3.2.
</div>
<div id="ref-R-aTSA" class="csl-entry">
Qiu D. 2015. <em>aTSA: Alternative Time Series Analysis</em>. Ed ke-R package version 3.1.2.
</div>
<div id="ref-R-ggplot2" class="csl-entry">
Wickham H, Chang W, Henry L, Pedersen TL, Takahashi K, Wilke C, Woo K, Yutani H, Dunnington D. 2021. <em>ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics</em>. Ed ke-R package version 3.3.5.
</div>
<div id="ref-R-dplyr" class="csl-entry">
Wickham H, François R, Henry L, Müller K. 2022. <em>dplyr: A Grammar of Data Manipulation</em>. Ed ke-R package version 1.0.8.
</div>
<div id="ref-R-timeDate" class="csl-entry">
Wuertz D, Setz T, Chalabi Y, Maechler M, Byers JW. 2018. <em>timeDate: Rmetrics - Chronological and Calendar Objects</em>. Ed ke-R package version 3043.102.
</div>
<div id="ref-R-strucchange" class="csl-entry">
Zeileis A, Leisch F, Hornik K, Kleiber C. 2019. <em>strucchange: Testing, Monitoring, and Dating Structural Changes</em>. Ed ke-R package version 1.5-2.
</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="pemulusan.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-praeksplor.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
